version: 2.1

jobs:
  cypress_tests_cli:
    parallelism: 5
    docker:
      - image: cypress/browsers:latest
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v5-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v5-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache
      - run:
          name: Build
          command: npm run build
      - run:
          name: Cypress Tests with @currents/cli
          command: |
            cd examples/webapp
            npm install @currents/cli
            MSG=`git log -1 --pretty=%B`
            COMMIT_INFO_MESSAGE="[@currents/cli] $MSG" npx currents run --record --parallel \
            --spec "./cypress/e2e*/*.spec.js" \
            --tag "currents-cli,circleCI" \
            --browser chrome --key $CURRENTS_RECORD_KEY \
            --ci-build-id $CIRCLE_WORKFLOW_ID-$CIRCLE_WORKFLOW_JOB_ID

  cypress_tests_cloud:
    parallelism: 5
    docker:
      - image: cypress/browsers:latest
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          key: v5-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v5-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache
      - run:
          name: Build
          command: npm run build
      - run:
          name: Cypress Tests with cypress-cloud
          command: |
            cd examples/webapp
            MSG=`git log -1 --pretty=%B`
            COMMIT_INFO_MESSAGE="[cypress-cloud] $MSG" node ../../packages/cypress-cloud/out/bin/index.js run --record --parallel \
            --spec "./cypress/e2e*/*.spec.js" \
            --tag "cypress-cloud,circleCI" \
            --browser chrome --key $CURRENTS_RECORD_KEY \
            --ci-build-id $CIRCLE_WORKFLOW_ID-$CIRCLE_WORKFLOW_JOB_ID

workflows:
  cypress:
    jobs:
      - cypress_tests_cli:
          context: currents
      - cypress_tests_cloud:
          context: currents
